name: 18 - Docker Custom Actions workflow

on:
  workflow_dispatch:
    inputs:
      url:
        default: https://www.google.com
        description: URL to ping
        required: true

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        id: ping-url
        with:
          url: ${{ inputs.url }}
      - name: Output Ping URL result
        run: |
          echo "Status of Ping URL is: ${{ steps.ping-url.outputs.url-reachable }}"
          
